"""empty message

Revision ID: cd73af59f006
Revises: 9dd7f71c4867
Create Date: 2018-08-01 16:47:41.247152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd73af59f006'
down_revision = '9dd7f71c4867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift',
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_name', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('book_title', sa.String(length=50), nullable=True),
    sa.Column('book_author', sa.String(length=30), nullable=True),
    sa.Column('book_img', sa.String(length=50), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('requester_nickname', sa.String(length=20), nullable=True),
    sa.Column('gifter_id', sa.Integer(), nullable=True),
    sa.Column('gift_id', sa.Integer(), nullable=True),
    sa.Column('gifter_nickname', sa.String(length=20), nullable=True),
    sa.Column('pending', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drift')
    # ### end Alembic commands ###
