"""empty message

Revision ID: efa4c423cb84
Revises: 9e3ad73a703b
Create Date: 2018-07-03 13:56:20.483066

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'efa4c423cb84'
down_revision = '9e3ad73a703b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wish',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('isbn', sa.String(length=15), nullable=False),
                    sa.Column('launched', sa.Boolean(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('create_time', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wish')
    # ### end Alembic commands ###
